public class ContactAccountInsert {
	public static void Con(list<Contact>ConList){			
		list<Contact>AccList = New List<Contact>();
        if(RecursiveContact.Recursion == True){
        for(Contact Con1 : ConList){
				Contact Acc = New Contact();
				       acc.LastName = 'HVDHyJeevan54845';
     				   acc.Phone = '218745';
        			  
 						Acclist.add(Acc);
            RecursiveContact.Recursion = False;
            
						}
            insert AccList;
			
        }
			}
    
		}