public class FirstClass {
    
    
	//Variable declaration
	public static integer VarSum;
    public Static integer VarSubs;
    
    //sum
    Public static void  Addition (integer NumA, integer NumB){
        VarSum = NumA + NumB;
       system.debug('The Addition of two numbers = ' +VarSum);
		        
    }	
    Public static void Substraction(integer Numc, integer NumD){
    VarSubs = NumC - NumD;
    system.debug('The Substraction = ' +VarSubs);
}
}